spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

  #H2 settings
  h2:
    console:
      enabled: true
      path: /h2-console


